{
 "title": "Community Engineering Scorecard",
 "time": { "from": "2023-05-01T00:00:00.000Z", "to": "2023-08-01T23:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "category", "label": "Category", "query": { "query": "" } },
   {
    "name": "start",
    "label": "Start Date",
    "query": "start of 2022q1 : 2022-02-01, start of 2022q2 : 2022-05-01, start of 2022q3 : 2022-08-01, start of 2022q4 : 2022-11-01, start of 2023q1 : 2023-02-01, start of 2023q2 : 2023-05-01, start of 2023q3 : 2023-08-01, start of 2023q4 : 2023-11-01"
   },
   {
    "name": "end",
    "label": "End Date",
    "query": "end of 2022q1 : 2022-05-01, end of 2022q2 : 2022-08-01, end of 2022q3 : 2022-11-01, end of 2022q4 : 2023-02-01, end of 2023q1 : 2023-05-01, end of 2023q2 : 2023-08-01, end of 2023q3 : 2023-11-01, end of 2023q4 : 2024-02-01"
   },
   {
    "name": "copy_of_category",
    "label": "OLD-Category",
    "query": "installation : 18, alerting : 60, piechart : 50, timeseries : 24, no subcategory : 33, loki : 41, grafana cloud : 34, tempo : 40, plugin development : 30, documentation : 39, lounge : 42, configuration : 20, azure monitor : 43, graphite : 13, elasticsearch : 14, authentication : 22, time series : 24, table : 26, stat : 25, prometheus : 15, influxDB : 11, development/api : 44, plugins - publishing : 45, plugins - showcase : 46, plugins - announcements : 47, gauge : 51, bar chart : 52, bar gauge : 53, mysql : 54, postgres : 55, cloudwatch : 56, graph (old) : 57, zabbix : 58, mssql : 59, dashboards : 61, explore : 62, live : 63, geomap : 64, data-links : 65"
   }
  ]
 },
 "panels": [
  { "title": "Community Forum Response Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Rate per Category: from ${start} to ${end}",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groq": "*",
     "parser": "backend",
     "root_selector": "rows",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://community.grafana.com/admin/plugins/explorer/queries/28/run?params=%7B%22date_from%22%3A%22${start}%22%2C%22date_to%22%3A%22${end}%22%2C%22cat%22%3A%22${category}%22%7D",
     "url_options": { "body_content_type": "application/json", "body_type": "none", "data": "", "method": "POST" }
    },
    {
     "groq": "*",
     "parser": "backend",
     "root_selector": "rows",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://community.grafana.com/admin/plugins/explorer/queries/29/run?params=%7B%22date_from%22%3A%22${start}%22%2C%22date_to%22%3A%22${end}%22%2C%22cat%22%3A%22${category}%22%7D",
     "url_options": { "body_content_type": "application/json", "body_type": "none", "data": "", "method": "POST" }
    }
   ]
  },
  {
   "title": "\"${category}\" category: topics with no response: 22Q4",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "groq": "*",
     "parser": "simple",
     "root_selector": "rows",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://community.grafana.com/admin/plugins/explorer/queries/14/run?params=%7B%22date_from%22%3A%22${start}%22%2C%22date_to%22%3A%22${end}%22%2C%22cat%22%3A%22${category}%22%7D",
     "url_options": {
      "body_content_type": "application/json",
      "body_form": [],
      "body_type": "x-www-form-urlencoded",
      "data": "",
      "headers": [
       { "key": "x-discourse-route", "value": "query/run" }
      ],
      "method": "POST",
      "params": []
     }
    }
   ]
  },
  {
   "title": "Response Rate: ALL categories",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "category": "33",
     "period": "monthly",
     "reportName": "topics_with_no_response.json",
     "searchArea": "topics_posts",
     "searchSort": "latest",
     "userQuery": "topPublicUsers"
    },
    {
     "category": "33",
     "period": "monthly",
     "reportName": "topics.json",
     "searchArea": "topics_posts",
     "searchSort": "latest",
     "userQuery": "topPublicUsers"
    }
   ]
  },
  {
   "title": "Replies Needed to Reach a Response Rate of:",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Top 20 Posts in $category Category: from ${start} to ${end}",
   "type": "table",
   "description": "Taken from discource datasource plugin",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "rows",
     "source": "url",
     "type": "json",
     "url": "https://community.grafana.com/admin/plugins/explorer/queries/38/run?params=%7B%22date_from%22%3A%22${start}%22%2C%22date_to%22%3A%22${end}%22%2C%22cat%22%3A%22${category}%22%7D",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "POST" }
    }
   ]
  },
  {
   "title": "Top 20 Posts from Q1 2023",
   "type": "table",
   "description": "Taken from discource datasource plugin",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "rows",
     "source": "url",
     "type": "json",
     "url": "https://community.grafana.com/admin/plugins/explorer/queries/7/run",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "POST" }
    }
   ]
  },
  {
   "title": "Top 20 Solution Status - Q1 2023",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "targets": [
    { "panelId": 51 }
   ]
  },
  {
   "title": "Top 20 Solution Status - Q1 2023",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 51 }
   ]
  },
  { "title": "Repo Stats: grafana/grafana ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "\"unlabeled\" issues for triage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.unlabeled.gauge, '7d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "\"needs more info\" issues",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.needs_more_info.gauge, '1d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "\"needs investigation\" + \"triage/needs-confirmation\" issues",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.needs_investigation.gauge, '1d', 'avg', false), 2)"
    },
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.triage_needs_confirmation.gauge, '1d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "TOTAL open issues",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "diffSeries(#A, #B)",
     "targetFull": "diffSeries(summarize(gh_action.repo.open_issues_count, '1d', 'avg', false), summarize(gh_action.issue_query.open_prs.gauge, '1d', 'avg', false))"
    }
   ]
  },
  {
   "title": "\"unlabeled\" issues for triage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.unlabeled.gauge, '1d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "\"needs more info\" issues",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.needs_more_info.gauge, '1d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "\"triage/needs-confirmation\" + \"needs investigation\" issues",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 34 }
   ]
  },
  {
   "title": "TOTAL open issues",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "diffSeries(#A, #B)",
     "targetFull": "diffSeries(summarize(gh_action.repo.open_issues_count, '1d', 'avg', false), summarize(gh_action.issue_query.open_prs.gauge, '1d', 'avg', false))"
    }
   ]
  },
  {
   "title": "issues with no assigned project",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "options": {
      "query": "label:\"needs investigation\" no:project is:open"
     },
     "owner": "grafana",
     "repository": "grafana"
    },
    {
     "options": {
      "query": "label:\"triage/needs-confirmation\" no:project is:open"
     },
     "owner": "grafana",
     "repository": "grafana"
    }
   ]
  },
  {
   "title": "Legacy Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "% top 20 posts w/solution",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "spreadsheet": "1W33YtV9zm5Qa6Q79TZXZq-RXLze1FFusyaRr9_6Z2Hw"
      }
     ]
    },
    {
     "title": "Dashboard Category with replies BETWEEN 1 and 3 Q1 2023",
     "type": "table",
     "description": "The reason to create this query is to get those post which do get an initial response either by another user OR the same user and then never get inside the community scorecard.\n",
     "gridPos": { "h": 8, "w": 20, "x": 1, "y": 57 },
     "targets": [
      {
       "parser": "backend",
       "root_selector": "rows",
       "source": "url",
       "type": "json",
       "url": "https://community.grafana.com/admin/plugins/explorer/queries/30/run",
       "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "POST" }
      }
     ]
    }
   ]
  }
 ]
}