{
 "title": "MongoDB Movie Database",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "_movie",
    "label": "Movie",
    "query": {
     "query": "sample_mflix.movies.aggregate([\n    {\"$match\": {year: {\"$gt\": 2011}}},\n    {\"$project\": {_id: 0, _movie_year: \"$title\"}}\n])"
    }
   },
   {
    "name": "_year",
    "label": "Movie",
    "query": {
     "query": "sample_mflix.movies.aggregate([\n    {\"$match\": {year: {\"$gt\": 2011}}},\n    {\"$project\": {_id: 0, _movie_year: {\"$toString\":\"$year\"}}}\n])"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Awards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "sample_mflix.movies.find({title: \"$_movie\", year: $_year}, {\"awards\":1})"
    }
   ]
  },
  {
   "title": "IMDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "sample_mflix.movies.find({title: \"$_movie\", year: $_year}, {\"imdb.rating\": 1, \"imdb.votes\": 1})"
    }
   ]
  },
  {
   "title": "Tomato Meter",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "sample_mflix.movies.find({\"title\":\"$_movie\", year: $_year}, {\"tomatoes.viewer.meter\": 1})"
    }
   ]
  },
  {
   "title": "Tomatoes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "sample_mflix.movies.find({title: \"$_movie\"}, {tomatoes: 1})"
    }
   ]
  },
  {
   "title": "Cast",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "sample_mflix.movies.aggregate([\n    { \"$match\": {title: \"$_movie\"}},\n    { \"$project\" : {\"cast\": 1, \"_id\": 0}},\n    { \"$unwind\" : \"$cast\"}]\n)"
    }
   ]
  },
  {
   "title": "Directors",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 11 },
   "targets": [
    {
     "query": "sample_mflix.movies.aggregate([\n    { \"$match\": {title: \"$_movie\", year: $_year}},\n    { \"$project\" : {\"directors\": 1, \"_id\": 0}},\n    { \"$unwind\" : \"$directors\"}]\n)"
    }
   ]
  },
  {
   "title": "Writers",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 11 },
   "targets": [
    {
     "query": "sample_mflix.movies.aggregate([\n    { \"$match\": {title: \"$_movie\", year: $_year}},\n    { \"$project\" : {\"writers\": 1, \"_id\": 0}},\n    { \"$unwind\" : \"$writers\"}]\n)"
    }
   ]
  },
  {
   "title": "Critics Consensus",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "query": "sample_mflix.movies.find({\"title\":\"$_movie\", year: $_year}, {\"tomatoes.consensus\": 1, _id: 0})"
    }
   ]
  },
  {
   "title": "Plot",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "sample_mflix.movies.find({\"title\":\"$_movie\"}, {plot: 1, _id: 0})"
    }
   ]
  }
 ]
}