{
 "title": "Citibike Example: Overview",
 "description": "Example use of Grafana of Business Intelligence, leveraging BigQuery's public citibike dataset and dbt Cloud",
 "time": { "from": "2017-04-01T00:00:00.000Z", "to": "2018-05-31T23:59:59.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>Citibike Dashboard Example:</h1>\n\n  <h3>BigQuery Public Dataset</h3>\n  \n  - Data: bigquery-public-data.new_york_citibike\n  - Timeframe: subset of data from Apr'17 - May'18\n  - Transformation: dbt cloud (developer tier) - [dbt project github repo](https://github.com/chs820/grafana_blog_bi)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<div>\n  <img src=\"https://grafana.com/static/assets/internal/grafana_logo-web.svg\">\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Last Updated",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "select\n  max(date_stamp) as last_updated\nfrom\n  chris-analytics-testing.dbt_cshih.agg_trips_by_station_daily"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\">\n    <p style=\"text-align: center; font-size: 150%; padding: 0px; margin: 0px;\">\n        <b>Overview</b>\n    </p>\n    <p style=\"text-align: center; font-size: 95%; padding: 0px; margin: 0px\">\n        <em>(updates based on top time selection)</em>\n    </p> \n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Daily Summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Daily Citibike Trip Duration (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "with\n\ndaily_trips as (\n\n    select\n        cast(u.date_stamp as timestamp) as date_stamp\n        ,sum(u.total_trips) as total_trips\n        ,sum(u.total_trip_duration_minutes) as total_trip_duration_minutes\n        ,1.0 * sum(u.total_trip_duration_minutes) / sum(u.total_trips) as average_trip_duration_minutes\n    from\n        chris-analytics-testing.dbt_cshih.agg_trips_by_user_type_daily u\n    group by 1\n    order by 1\n\n),\n\nfinal as (\n\n    select\n        date_stamp\n        ,total_trips\n        ,total_trip_duration_minutes\n        ,average_trip_duration_minutes\n        ,avg(total_trips) over (order by date_stamp asc rows between 6 preceding and current row) as trailing_7_day_ma_trips\n        ,avg(total_trip_duration_minutes) over (order by date_stamp asc rows between 6 preceding and current row) as trailing_7_day_ma_duration\n\n    from\n        daily_trips\n\n)\n\nselect *\nfrom final\nwhere $__timeFilter(date_stamp)\n"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\">\n    <p style=\"text-align: center; font-size: 150%; padding: 0px; margin: 0px;\">\n        <b>Trip Stats by Rider Characteristics</b>\n    </p>\n    <p style=\"text-align: center; font-size: 95%; padding: 0px; margin: 0px\">\n        <em>(updates based on top time selection)</em>\n    </p> \n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Daily Trip Duration (minutes)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "rawSql": "with\n\ntrips as (\n\n    select\n        *\n        ,cast(date_stamp as timestamp) as time\n    from chris-analytics-testing.dbt_cshih.agg_trips_by_user_type_daily\n\n),\n\nfinal as (\n\n    select\n        avg(case when t.user_type = 'Customer' then t.total_trip_duration_minutes end) as customer_daily_trip_duration\n        ,avg(case when t.user_type = 'Subscriber' then t.total_trip_duration_minutes end) as subscriber_daily_trip_duration\n\n        ,avg(case when t.user_type = 'Customer' then t.total_trips end) as customer_daily_trips\n        ,avg(case when t.user_type = 'Subscriber' then t.total_trips end) as subscriber_daily_trips\n\n        ,avg(case when t.user_type = 'Customer' then t.average_trip_duration_minutes end) as customer_daily_average_trip_duration\n        ,avg(case when t.user_type = 'Subscriber' then t.average_trip_duration_minutes end) as subscriber_daily_average_trip_duration\n    from\n        trips t\n    where\n        $__timeFilter(time)\n\n)\n\nselect *\nfrom final\n"
    }
   ]
  },
  {
   "title": "Daily Trips",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 27 }
   ]
  },
  {
   "title": "Average Trip Duration (minutes)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 27 }
   ]
  },
  {
   "title": "Heatmap Distribution: Daily Trips by Rider Age",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "location": "US",
     "rawSql": "with\n\nfinal as (\n    \n    select\n        cast(date_trunc(t.date_stamp, week) as timestamp) as time\n        ,sum(case when t.rider_age between 20 and 24 then t.total_trip_duration_minutes end) as age_20_24\n        ,sum(case when t.rider_age between 25 and 29 then t.total_trip_duration_minutes end) as age_25_29\n        ,sum(case when t.rider_age between 30 and 34 then t.total_trip_duration_minutes end) as age_30_34\n        ,sum(case when t.rider_age between 35 and 39 then t.total_trip_duration_minutes end) as age_35_39\n        ,sum(case when t.rider_age between 40 and 44 then t.total_trip_duration_minutes end) as age_40_44\n        ,sum(case when t.rider_age between 45 and 49 then t.total_trip_duration_minutes end) as age_45_49\n        ,sum(case when t.rider_age between 50 and 54 then t.total_trip_duration_minutes end) as age_50_54\n        ,sum(case when t.rider_age between 55 and 59 then t.total_trip_duration_minutes end) as age_55_59\n        ,sum(case when t.rider_age between 60 and 64 then t.total_trip_duration_minutes end) as age_60_64\n        ,sum(case when t.rider_age >= 65 then t.total_trip_duration_minutes end) as age_65\n    from\n        chris-analytics-testing.dbt_cshih.agg_trips_by_age_daily t\n    group by 1\n\n)\n\nselect *\nfrom final\nwhere $__timeFilter(time)\n"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\">\n    <p style=\"text-align: center; font-size: 150%; padding: 0px; margin: 0px;\">\n        <b>Bike Station Details</b>\n    </p>\n    <p style=\"text-align: center; font-size: 95%; padding: 0px; margin: 0px\">\n        <em>(updates based on top time selection)</em>\n    </p> \n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Most popular stations: Trip Origins",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "with\n\nstation_trips as (\n\n    select\n        cast(t.date_stamp as timestamp) as time\n        ,t.station_name\n        ,t.station_latitude\n        ,t.station_longitude\n        ,t.starting_trips\n        ,t.ending_trips\n    from\n        chris-analytics-testing.dbt_cshih.agg_trips_by_station_daily t\n\n),\n\nfinal as (\n\n    select\n        station_latitude\n        ,station_longitude\n        ,station_name\n        ,avg(starting_trips) as average_daily_starting_trips\n        ,avg(ending_trips) as average_daily_ending_trips\n    from\n        station_trips\n    where\n        $__timeFilter(time)\n    group by 1,2,3\n\n)\n\nselect *\nfrom final\nwhere average_daily_starting_trips > 0\n\n"
    }
   ]
  },
  {
   "title": "Most popular stations: Trip Destinations",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "with\n\nstation_trips as (\n\n    select\n        cast(t.date_stamp as timestamp) as time\n        ,t.station_name\n        ,t.station_latitude\n        ,t.station_longitude\n        ,t.starting_trips\n        ,t.ending_trips\n    from\n        chris-analytics-testing.dbt_cshih.agg_trips_by_station_daily t\n\n),\n\nfinal as (\n\n    select\n        station_latitude\n        ,station_longitude\n        ,station_name\n        ,avg(starting_trips) as average_daily_starting_trips\n        ,avg(ending_trips) as average_daily_ending_trips\n    from\n        station_trips\n    where\n        $__timeFilter(time)\n    group by 1,2,3\n\n)\n\nselect *\nfrom final\nwhere average_daily_ending_trips > 0\n"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 71 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\">\n    <p style=\"text-align: center; font-size: 150%; padding: 0px; margin: 0px;\">\n        <b>Data & Analytics News</b>\n    </p>\n    <p style=\"text-align: center; font-size: 95%; padding: 0px; margin: 0px\">\n        <em>(RSS Feeds)</em>\n    </p> \n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Grafana News",
   "type": "news",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "location": "US",
     "rawSql": "with\n\nstation_trips as (\n\n    select\n        cast(t.date_stamp as timestamp) as time\n        ,t.station_name\n        ,t.station_latitude\n        ,t.station_longitude\n        ,t.starting_trips\n        ,t.ending_trips\n    from\n        grafanablog.dbt_cshih.agg_trips_by_station_daily t\n\n),\n\nfinal as (\n\n    select\n        station_latitude\n        ,station_longitude\n        ,station_name\n        ,avg(starting_trips) as average_daily_starting_trips\n        ,avg(ending_trips) as average_daily_ending_trips\n    from\n        station_trips\n    where\n        $__timeFilter(time)\n    group by 1,2,3\n\n)\n\nselect *\nfrom final\nwhere average_daily_starting_trips > 0\n\n"
    }
   ]
  },
  {
   "title": "Analytics Engineering Roundup",
   "type": "news",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "location": "US",
     "rawSql": "with\n\nstation_trips as (\n\n    select\n        cast(t.date_stamp as timestamp) as time\n        ,t.station_name\n        ,t.station_latitude\n        ,t.station_longitude\n        ,t.starting_trips\n        ,t.ending_trips\n    from\n        grafanablog.dbt_cshih.agg_trips_by_station_daily t\n\n),\n\nfinal as (\n\n    select\n        station_latitude\n        ,station_longitude\n        ,station_name\n        ,avg(starting_trips) as average_daily_starting_trips\n        ,avg(ending_trips) as average_daily_ending_trips\n    from\n        station_trips\n    where\n        $__timeFilter(time)\n    group by 1,2,3\n\n)\n\nselect *\nfrom final\nwhere average_daily_starting_trips > 0\n\n"
    }
   ]
  }
 ]
}